### ISSUE TITLE
Track Ubuntu Bionic & Mint 19 incompatibilities

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#117]
Mint 19 will be based on Ubuntu 18.04. As 18.04 starts to approach Feature Freeze and release, we should take notes of incompatibilities between the Ansible playbook and any betas (and subsequent releases). None of these should be acted on now since things may change before official release.

https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule

Current notes:

- [x]  Aptitude is not installed in 18.04. This may need to be installed manually because I don't think Ansible adds support for `apt-get` until 2.4.
- [x] The syslog user gets picked up as a valid user since homedir is `/home/syslog` and the shell is `/usr/bin/nologin`. We may need to adjust how we detect valid users.
- [x] `gksu` is not installed by default in 18.04. This package is no longer recommended and `pkexec` should probably be used instead

**Comment by ripleymj** [comment]
syslog should be easy enough to fix by adding a 3rd criteria:
```
- name: Build real user list
  set_fact:
    real_users: >-
      {{ real_users|default([]) +
      [ {'user': item.key, 'homedir': item.value.4,
      'uid': item.value.1, 'gid': item.value.2 } ] }}
  with_dict: "{{ getent_passwd }}"
  when:
    - item.value.4 | match ("^/home/")
    - item.value.5 != "/bin/false"
```
