### ISSUE TITLE
USB hardware level

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#65]
Per @ChrisMayfield, we should be intentional about requiring the Extension Pack when packaging the VM, as most people won't need it. CS354 may require a better USB controller for moving Kinect data into the VM.

- [x] Remove USB 2.0 from the next image build
- [x] Add a warning/failure if EHCI/xHCI controllers exist during OEM script
- [x] Find a way to warn in the CS354 target of a missing EHCI/xHCI controller
- [x] Create a docs folder, and publish a How to Add Extensions and Upgrade USB markdown file

**Comment by kylelaker** [comment]
Do we want the EHCI/xHCI warning to be a libnotify notification or did you have something else in mind?

**Comment by ripleymj** [comment]
In theory, I like that we can do libnotify and move on, but I feel this may be worthy of the subtlety that zenity offers.

**Comment by kylelaker** [comment]
As far as the warning, I am not sure how to best go about it, so I'm hoping you have something in mind. The best I have though of is:

`roles/robot-pkgs/tasks/main.yml`
```
- name: Check for missing USB 2/3 controllers
  shell: lspci | grep -i -e EHCI -e xHCI
  register: lspci_output
  #failed_when: lspci_output.rc != 0
  changed_when: False
- name: Alert missing USB 2/3 controllers
  notify:
      - USB controllers warning
  when: lspci_output.rc != 0
```
`roles/robot-pkgs/handlers/main.yml`
```
- name: USB controllers warning
  command: >-
    zenity --warn --text "USB Controllers missing"
    "In order to effectively connect robots to the VM"
    "ECHI/xHCI controllers need to be installed from"
    "VirtualBox. See <a href='URL'>these instructions</a> for"
    "more information on how to install them"
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ real_users }}"
```
I feel like there is probably a *much* cleaner way of going about it. It feels dirty that checking the condition and notifying the handler are two separate tasks.
